x-db-env: &db-env
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_USER: "app_user"
  DB_PASSWORD: "app_password"
  DB_NAME: "ecommerce_db"
  DB_INSECURE: "true"
  MAX_IDLE_CONN: "10"
  MAX_OPEN_CONN: "10"

services:
  db:
    image: postgres:15-alpine
    container_name: ecommerce-db
    environment:
      POSTGRES_USER: "app_user"
      POSTGRES_PASSWORD: "app_password"
      POSTGRES_DB: "ecommerce_db"
    ports:
      - "5434:5432"
    volumes:
      - ecommerce-db-data:/var/lib/postgresql/data
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d ecommerce_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network

  migrations:
    build:
      context: ecommerce.managers.migrations
      dockerfile: Dockerfile
    environment:
      <<: *db-env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ecommerce-network

  user-manager:
    build:
      context: ecommerce.users.manager
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      <<: *db-env
      APP_NAME: "users-manager"
      APP_PORT: "50051"
      JWT_SECRET: "your_jwt_secret"
    depends_on:
      migrations:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50051"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network

  auth:
    build:
      context: ecommerce.auth
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_PORT: "8080"
      USER_MANAGER_HOST: "user-manager:50051"
    depends_on:
      migrations:
        condition: service_completed_successfully
      user-manager:
        condition: service_healthy
    networks:
      - ecommerce-network

  product-manager:
    build:
      context: ecommerce.products.manager
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      <<: *db-env
      APP_NAME: "products-manager"
      APP_PORT: "8081"
    depends_on:
      migrations:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network

  order-service:
    build:
      context: ecommerce.orders.manager
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      <<: *db-env
      APP_NAME: "orders-manager"
      APP_PORT: "8082"
      #AUTH_SERVICE_HOST: "auth:8080"
      USER_MANAGER_HOST: "user-manager:50051"
      PRODUCT_MANAGER_HOST: "http://product-manager:8081"
    depends_on:
      migrations:
        condition: service_completed_successfully
      user-manager:
        condition: service_healthy
      product-manager:
        condition: service_healthy
    networks:
      - ecommerce-network

volumes:
  ecommerce-db-data:

networks:
  ecommerce-network:
    driver: bridge