FROM golang:1.23.2-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /migrate ./src/main.go

FROM alpine:3.18
RUN apk add --no-cache tzdata ca-certificates bash
COPY --from=builder /migrate /migrate

ENTRYPOINT ["/migrate"]